### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by steenhulthin** [mhoyer/todomvc-aurelia#10]
The todo app does not work in Firefox (37.0.2). 

I get a 404 on: `http://todomvc.com/examples/aurelia/dist\bundled.js` when looking in the dev tools. In Chrome the url is `http://todomvc.com/examples/aurelia/dist/bundled.js` (forward slash in stead of backslash before `bundled.js`).

**Comment by mhoyer** [comment]
@steenhulthin thanks for reporting this. I'll have a look into it.

**Comment by mhoyer** [comment]
Just checked with latest version on master on FF41 and it looks okay for me. Release of Aurelia TodoMVC 0.2.0 will arrive soon.
