### ISSUE TITLE
Broken on todomvc.com

### ISSUE THREAD

**Issue by rsyring** [mhoyer/todomvc-aurelia#12]
Visiting: http://todomvc.com/examples/aurelia/

Results in no UI for me on the latest Firefox on Linux.

**Comment by mhoyer** [comment]
Thank you for reporting this. It's known and already addressed here:
https://github.com/tastejs/todomvc/issues/1492

And fixed here:
https://github.com/mhoyer/todomvc-aurelia/issues/10

Thus, I am waiting for https://github.com/tastejs/todomvc/pull/1545 to be picked. ;-)
