### ISSUE TITLE
jspm bundle-sfx and --minifiy does not work as expected

### ISSUE THREAD

**Issue by mhoyer** [mhoyer/todomvc-aurelia#4]
With `gulp build-bundle` a command like the following will be executed to create a single `bundled.js` containing all dependencies and the app specific js files:

```
jspm bundle dist/main dist/bundled.js --inject --skip-source-maps
```

This works. But two modifications to this command do not.
#### Creating self-extracting bundle

Running same command with `bundle-sfx` instead:

```
jspm bundle-sfx dist/main dist/bundled.sfx.js --inject --skip-source-maps
```

... and modifying the `index.html` to include only this new `bundle.sfx.js` produces loading error: 

```
bundled.sfx.js:311 Uncaught Module ./bundle not present.
```
#### Minifying the bundle

Running original command with additional `--minify` option:

```
jspm bundle dist/main dist/bundled.js --inject --skip-source-maps --minify
```

... produces in Chrome console:

```
dist\bundled.js:6 Uncaught TypeError: Cannot set property 'cache' of undefined
```

**Comment by juliocesar** [comment]
I'll second this. The same configuration that worked fine for `0.14`, after an update to `0.15.1`, `$ jspm bundle-sfx ./src/boot public/bundle.js` throws an error in-browser saying `Uncaught Module ./src/boot not present`.

**Comment by mhoyer** [comment]
Aurelia now ships with bundling wrapper. See: http://blog.durandal.io/2015/06/23/bundling-an-aurelia-application/ and wait for upcoming 0.2.0 of Aurelia TodoMVC.
